name: "auto-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel
      - name: Build
        run: |
          python -m build
          pip install dist/*.whl
          echo "PACKAGE_VERSION=$(python -c 'import whois21; print(whois21.__version__)')" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.PACKAGE_VERSION }}"
          title: "Auto Build"
          files: |
            dist/*
